name: 'Terraform Template Composite Action'
description: 'Terraform Template Composite Action'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
#   steps:
#   - run: echo Hello World
#     shell: bash

  defaults:
    run:
      working-directory: ./terraform

  env:
    ENVIRONMENT: unity-catalog


  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up latest version of Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Clone Config repot
      #uses: hashicorp/setup-terraform@v1
      run: |
        git clone https://github-dev.nwie.net/NationwideTest/Databricks_Automation_Config.git
        ls -ltra
        cat ./Databricks_Automation_Config/issue_submission/env.sh
        echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
        echo "BSA_SHORTNAME=$BSA_SHORTNAME" >> $GITHUB_ENV
        echo "DB_REGION=$DB_REGION" >> $GITHUB_ENV