name: 'Terraform Template Composite Action'
description: 'Terraform Template Composite Action'

runs:
  using: "composite"

  steps:
  
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.GH_TOKEN }}


    - name: Set up latest version of Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    - name: Clone Terraform Template Config repo
      run: |
        git clone https://github.com/robert-altmiller/terraform_template_config.git
        ls -ltra
        cat ./issue_submission/env.sh
        echo "ENVIRONMENT=$TF_VAR_environment" >> $GITHUB_ENV
        echo "Current TF_VAR_environment: ${{ env.TF_VAR_environment }}"
      shell: bash
      working-directory: ./terraform
