name: 'Terraform Template Composite Action'
description: 'Terraform Template Composite Action'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
#   steps:
#   - run: echo Hello World
#     shell: bash

  defaults:
    run:
      working-directory: ./terraform

  steps:

    - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}


    - name: Set up latest version of Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    - name: Clone Terraform Template Config repo
      run: |
        git clone https://https://github.com/robert-altmiller/terraform_template_config.git
        ls -ltra
        cat ./issue_submission/env.sh
        echo "ENVIRONMENT=$TF_VAR_environment" >> $GITHUB_ENV