name: Create a New Unity Catalog Storage Credential
description: UC Storage Credential Create Request Form
labels: [storage_credential]

title: "Create Unity Catalog Storage Credential Request Form"

body:
- type: dropdown
  id: create-delete-action
  attributes:
    label: Select to Create or Destroy Resource
    options:
      - Create
      - Destroy
  validations:
    required: True

- type: input
  id: storage-credential-name
  attributes:
    label: Please Enter the Storage Credential (SC) Name
  validations:
    required: True

- type: input
  id: iam-role-arn
  attributes:
    label: Please Enter the Integrated Access Management (IAM) Role AWS ARN?
  validations:
    required: True

- type: input
  id: principal-name
  attributes:
    label: Please Enter the Principal or Group Name for SC Access
  validations:
    required: True

- type: checkboxes
  id: principal-name-permissions
  attributes:
    label: Please Select the Grants for the Principal or Group Name
    options:
      - label: CREATE_EXTERNAL_TABLE
        required: False
      - label: CREATE_EXTERNAL_VOLUME
        required: False
      - label: CREATE_MANAGED_STORAGE
        required: False
      - label: READ_FILES
        required: False
      - label: WRITE_FILES
        required: False
      - label: ALL_PRIVILEGES
        required: False
    validations:
      required: True