name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      github_var_input:
        description: 'deploy environment'
        required: true
        default: 'dev'
  
  push:
    branches:
      - main


jobs:
  deploy:
    name: 'terraform plan'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform

    steps:

    # checkout repository v2
    - name: Checkout repository
      uses: actions/checkout@v3
    
      # setup terraform
    - name: setup terraform
      uses: hashicorp/setup-terraform@v1
    
    # terraform init
    - name: terraform init
      run: terraform init
      env:
        TF_VAR_aws_region: '${{ secrets.AWS_REGION }}'
        TF_VAR_aws_access_key_id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        TF_VAR_aws_access_key_secret: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'

    # terraform validate
    - name: terraform validate
      run: terraform validate

    # terraform init
    - name: terraform plan
      run: terraform plan
  
    # - name: List Files in Working Directory
    #   run: ls -la './terraform'
      
    # terraform apply
    - name: terraform apply
      run: |
        terraform apply --auto-approve
      env: 
        TF_VAR_aws_region: '${{ secrets.AWS_REGION }}'
        TF_VAR_aws_access_key_id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        TF_VAR_aws_access_key_secret: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
  