name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      github_var_input:
        description: 'Deploy environment'
        required: true
        default: 'dev'
  
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    env:
      TF_VAR_environment: ${{ secrets.ENVIRONMENT }}
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_access_key_secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_databricks_instance: ${{ secrets.DATABRICKS_INSTANCE }}
      TF_VAR_databricks_client_ids: '{"dev": ${{ secrets.DATABRICKS_CLIENT_ID_DEV }}, "prod": ${{ secrets.DATABRICKS_CLIENT_ID_PROD }}}'
      TF_VAR_databricks_client_secrets: '{"dev": ${{ secrets.DATABRICKS_CLIENT_SECRET_DEV }}, "prod": ${{ secrets.DATABRICKS_CLIENT_SECRET_PROD }}}'
      TF_VAR_databricks_admin_login: ${{ secrets.DATABRICKS_ADMIN_LOGIN }}
      TF_VAR_databricks_admin_password: ${{ secrets.DATABRICKS_ADMIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
    
      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: |
          terraform apply --auto-approve