name: Process Storage Credential Request

on:
  issues:
    types: opened
concurrency: 'main'

jobs:
  place_order:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/storage-credential-request.yml
        
      - run: cat ${HOME}/issue-parser-result.json

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > submission/submission.json

      - run: cat submission/submission.json

      - name: Fetch JSON file from the source repo
        run: |
          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github.v3.raw" -o storage_credential.json "https://api.github.com/repos/owner/source-repo/contents/path_to_file.json"

      - name: Commit submission request changes
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/robert-altmiller/terraform_template.git
          git pull && \
          git add submission/submission.json && \
          git commit -m 'new infrastructure submission' && \
          git push




