name: Process Storage Credential Request

on:
  issues:
    types: opened
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: false

jobs:
  place_order:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/storage-credential-request.yml
        
      - run: cat ${HOME}/issue-parser-result.json

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > ../../submission/submission2.json

      - run: cat ../submission/submission2.json

      - name: Commit changes
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \
          git add submission.json && \
          git commit -m 'new infrastructure submission' && \
          git push